### ISSUE TITLE
Markdown needs improvement

### ISSUE THREAD

**Issue by chrisbrickhouse** [Risley-Propagandist/Risley-Charter#3]
If anyone wants to fork the markdown and work on it, that would be lovely because right now there's a good amount of it that is sub par.

**Comment by scarbunkle** [comment]
Two versions makes amending sloppy.  Decided to stick to LaTeX version as current supported format, convert readme to tracking file status.  If someone wants to create a pretty web-readable markdown format in the future, the option is available.
